services:
  cube_api:
    build: .
    ports:
      - 4000:4000
      - 15432:15432
    environment:
      - CUBEJS_DB_TYPE=postgres
      - CUBEJS_DB_HOST=${CUBEJS_DB_HOST}
      - CUBEJS_DB_NAME=${CUBEJS_DB_NAME}
      - CUBEJS_DB_USER=${CUBEJS_DB_USER}
      - CUBEJS_DB_PASS=${CUBEJS_DB_PASS}
      - CUBEJS_DB_PORT=${CUBEJS_DB_PORT}
      - CUBEJS_DB_SSL=true
      - CUBEJS_DEV_MODE=true
      - PATH=/opt/venv/bin:$PATH
    volumes:
      - .:/cube/conf
    working_dir: /cube/conf/cube_project